### ISSUE TITLE
割り算バグ

### ISSUE THREAD

**Issue by nanaka0012** [nanaka0012/enpit_git_lecture#2]
## 操作手順
30/15したら
450になった

## 本来の想定
30/15したら
2になってほしい

## 操作環境
* OS
* OSバージョン
* ブラウザ
* ブラウザバージョン

**Comment by PastaSoba** [comment]
## 操作手順
2.4 ÷ 1.2 （小数点以下そのまま）
2.88 になった

## 本来の想定
2.4 ÷ 1.2 （小数点以下そのまま）
2.0 になってほしい


## 操作環境
* OS
* OSバージョン
* ブラウザ
* ブラウザバージョン
